# Default Setting
spring:
  servlet:
    multipart:
      max-file-size: 10MB
# mybatis
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.uahage.api.domain
  configuration:
    map-underscore-to-camel-case: true

---
spring:
  profiles:
    active: dev
---
